name: Release

permissions:
  contents: write
  repository-projects: write

on:
  workflow_dispatch:
    inputs:
      application_version:
        description: 'Provide new version of application'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run unit test
        run: ./mvnw -B -Ddockerfile.skip=true test --file pom.xml

      - name: Build docker
        run: ./mvnw package -Dskip.ut=true -Dmaven.main.skip

      - name: Run cucumber tests
        env:
          AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
          FRONTEND_BASE_URL: ${{ vars.FRONTEND_BASE_URL }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          MAIL_SENDER_ADDRESS: ${{ secrets.MAIL_SENDER_ADDRESS }}
        run: ./mvnw -B -Ddockerfile.skip=true -Dskip.ut=true verify --file pom.xml

      - name: Adjust version and push release
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          ./mvnw versions:set -DremoveSnapshot
          CURRENT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          git checkout -b release-$CURRENT_VERSION
          git commit -am "Release of version $CURRENT_VERSION."
          git tag $CURRENT_VERSION
          git push -u origin release-$CURRENT_VERSION
          git push origin $CURRENT_VERSION

      - name: Adjust version and push to develop
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout develop
          ./mvnw versions:set -DnewVersion=${{ inputs.application_version }}-SNAPSHOT
          git commit -am "Update of version after release to ${{ inputs.application_version }}-SNAPSHOT."
          git tag "${{ inputs.application_version }}-SNAPSHOT"
          git push
          git push origin "${{ inputs.application_version }}-SNAPSHOT"
